version: '3'

services:
    nginx:
        image: nginx:latest
        environment:
            - TZ=Asia/Shanghai
        # 端口映射
        ports:
            - "80:80"
        # 依赖关系 先跑php
        depends_on:
            - "php"
        # 数据卷
        volumes:
            # 映射主机./conf.d目录到容器/etc/nginx/conf.d目录
            - "$PWD/nginx/conf.d:/etc/nginx/conf.d"
            - "$PWD/nginx/project:/var/www/html"
        # 容器名称
        container_name: "compose-nginx"
    php:
        build: ./php
        # image指定build Dockerfile生成镜像的名称
        image: php:7.2-fpm-mysqli
        environment:
            - TZ=Asia/Shanghai
        ports:
            - "9000:9000"
        volumes:
            - "$PWD/nginx/project:/var/www/html"
        depends_on:
            - "redis"
        container_name: "compose-php"
    redis:
        command: redis-server --bind 0.0.0.0 --databases 32 # /data/redis.conf
        image: redis:3.2-alpine
        volumes:
          - ./redis/db:/data
        ports:
          - 6379:6379
        container_name: "compose-redis"
